/// ไอคอนทั้งชุดของแอป — เพิ่ม/เปลี่ยนที่นี่ที่เดียว หน้าอื่นห้าม import จาก lucide-react ตรง ๆ
export {
  LayoutDashboard as IconDashboard,
  Package as IconProduct,
  PackagePlus as IconStockIn,
  PackageMinus as IconStockOut,
  ChartColumn as IconReports,
  Users as IconUsers,
  Settings as IconSettings,
  Search as IconSearch,
  Plus as IconPlus,
  Pencil as IconEdit,
  Trash2 as IconTrash,
  TriangleAlert as IconWarning,
  LogOut as IconLogout,
  ChevronDown as IconChevronDown,
  ArrowDownToLine as IconArrowIn,
  ArrowUpFromLine as IconArrowOut,
  Boxes as IconBoxes,
  Wallet as IconWallet,
  Loader2 as IconSpinner,
  CircleUser as IconUser,
  Mail as IconMail,
  LockKeyhole as IconLock,
  ArrowLeft as IconBack,
  CircleCheck as IconCheck,
  ShoppingCart as IconPos,
  ReceiptText as IconReceipt,
  Calculator as IconCalculator,
  Tags as IconCategory,
  LayoutGrid as IconTable,
  Bell as IconBell,
  Merge as IconMerge,
  ChefHat as IconKitchen,
  QrCode as IconQr,
  Store as IconStore,
  CreditCard as IconCard,
  BookOpen as IconMenu,
  Banknote as IconCash,
  // Phase 14a — onboarding / คำเชิญ / ผู้ดูแลแพลตฟอร์ม
  Send as IconSend,
  ShieldCheck as IconShield,
  Ban as IconBan,
  Copy as IconCopy,
  UserPlus as IconUserPlus,
  // Phase 14c — ร้านหลายสาขา (Brand)
  Building2 as IconBrand,
  // Phase 15b — แนบสลิป
  Camera as IconCamera,
  // Phase 17a — อัปโหลดรูปเมนู/โลโก้
  ImagePlus as IconImagePlus,
  // เมนูลิ้นชักบนมือถือ (2026-09-17 — โครงหลังร้านรองรับจอเล็ก)
  Menu as IconHamburger,
  X as IconClose,
} from "lucide-react"
